### ISSUE TITLE
Change README File

### ISSUE THREAD

**Issue by MariMaxVR** [Max-Max-Company/Seminar3-HW#1]
Изменить файл README в проекте добавив полезную информацию. Все действия производить в отдельной ветке, по решению задачи выполнить запрос на слияние и отчитаться по задаче.

**Comment by GreenDragonVR** [comment]
Задачу принял к выполнению.

**Comment by GreenDragonVR** [comment]
https://github.com/Max-Max-Company/Seminar3-HW/issues/1 добавил полезную информацию и создал запрос на слияние, просьба проверить.

**Comment by MariMaxVR** [comment]
Всё отлично! Молодец! Задачу закрываю
